version: '3.4'

services:
   redis:
    container_name: beymen-redis
    image: redis:latest
    ports:
      - "6379:6379"

   beymengroupcase.servicea:
    container_name: beymen-servicea
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "18010:80" 
   
   beymengroupcase.serviceb:
    container_name: beymen-serviceb
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "18020:80" 
