version: '3.4'

services:
   redis:
    container_name: beymen-redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - beymen_network  

   beymengroupcase.servicea:
    container_name: beymen-servicea
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "18010:80" 
    networks:
      - beymen_network  
   
   beymengroupcase.serviceb:
    container_name: beymen-serviceb
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "18020:80" 
    networks:
      - beymen_network  

   beymengroupcase.configurationapi:
    container_name: beymen-configurationapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "18030:80" 
    networks:
      - beymen_network
 
   beymengroupcase.configurationapp:
    container_name: beymen-configurationapp
    restart: always
    ports:
      - "3000:80"
    networks:
      - beymen_network

networks:
  beymen_network:

