version: '3.4'

services:
  beymengroupcase.servicea:
    image: ${DOCKER_REGISTRY-}beymengroupcaseservicea
    build:
      context: .
      dockerfile: src/Services/BeymenGroupCase.ServiceA/Dockerfile

  beymengroupcase.serviceb:
    image: ${DOCKER_REGISTRY-}beymengroupcaseserviceb
    build:
      context: .
      dockerfile: src/Services/BeymenGroupCase.ServiceB/Dockerfile

